language: node_js
node_js:
- '6'
- '7'
cache:
  directories:
  - node_modules
script:
- npm install
- echo "$NPM_SECRET" >> ~/.npmrc
- npm test
deploy:
  provider: script
  script: "npm publish"
  on:
    tags: true
    repo: laundree/sdk
